### ISSUE TITLE
Tag Developer Guide: Still specifies Tag as a list.

### ISSUE THREAD

**Issue by vicelyav** [AY2425S1-CS2103-F09-3/tp#171]
Modify this:

Note: An alternative (arguably, a more OOP) model is given below. It has a Tag list in the AddressBook, which Person references. This allows AddressBook to only require one Tag object per unique tag, instead of each Person needing their own Tag objects.

Tag is no longer a list.

**Comment by ChinSekYi** [comment]
I just removed the whole line:
**Note:** An alternative (arguably, a more OOP) model is given below. It has a `Tag` in the `AddressBook`, which `Person` references. This allows `AddressBook` to only require one `Tag` object per unique tag, instead of each `Person` needing their own `Tag` objects.<br>

cuz i think its not needed
